  [[plugins]]
  repo = 'cespare/vim-toml'
  on_ft = 'toml'

  [[plugins]]
  repo = 'tmux-plugins/vim-tmux'
  on_ft = 'tmux'

##################
## Javascript ####
##################
  [[plugins]]
  repo = 'posva/vim-vue'
  on_ft = 'vue'

  [[plugins]]
  repo = 'elzr/vim-json'
  on_ft = 'json'
  hook_add = 'let g:vim_json_syntax_conceal = 0'

# React
  [[plugins]]
  repo = 'pangloss/vim-javascript'
  on_ft = ['javascript', 'javascript.jsx']

  [[plugins]]
  repo = 'maxmellon/vim-jsx-pretty'
  on_ft = ['javascript', 'javascript.jsx']

  [[plugins]]
  repo = 'alampros/vim-styled-jsx'
  on_ft = ['javascript', 'javascript.jsx']

  [[plugins]]
  repo = 'moll/vim-node'
  on_ft = ['javascript'] 

  [[plugins]]
  repo = 'hushicai/tagbar-javascript.vim'
  on_ft = ['javascript']
  hook_add = '''
    call system('npm i -g esctags')
  '''

##################
## Ruby ##########
##################
  [[plugins]]
  repo = 'tpope/vim-rails'
  on_ft = ['rb']
  [[plugins]]
  repo = 'ngmy/vim-rubocop'
  on_ft = ['rb']

##################
## Markdown ######
##################
  [[plugins]]
  repo = 'tyru/open-browser.vim'
  on_ft = ['md','markdown']
  hook_add = '''
    source ~/.config/nvim/plugins/open-browser.vim
  '''
  [[plugins]]
  repo = 'previm/previm'
  on_ft = ['md', 'markdown']
  depends = 'open-browser.vim'
  hook_add = '''
    source ~/.config/nvim/plugins/previm.vim
  '''
  [[plugins]]
  repo = 'plasticboy/vim-markdown'
  on_ft = ['md', 'markdown']
  hook_add = '''
    source ~/.config/nvim/plugins/vim-markdown.vim
  '''

