memodir = "/Users/kowwwwji/GoogleDrive/memo"
memotemplate = "/Users/kowwwwji/.config/memo/template.txt"
editor = "nvim"
column = 20
selectcmd = "peco"
# grepcmd = "/Applications/Visual\\ Studio\\ Code.app/Contents/Resources/app/node_modules/vscode-ripgrep/bin/rg -n --no-heading -S ${PATTERN} ${FILES}"
grepcmd = "grep -nH"
assetsdir = ""
pluginsdir = "/Users/kowwwwji/.config/memo/plugins"
templatedirfile = ""
templatebodyfile = ""
